name: Frontend

on:
  push:
  pull_request: ~

jobs:
  frontend:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        script: ['prod']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - run: /usr/local/bin/node -v

      # Install Flex as a global dependency to enable usage of extra.symfony.require
      # while keeping Flex recipes from applying
      - run: composer global require --no-scripts symfony/flex

      - run: composer config extra.symfony.require ~5.4.0

      - run: composer update --prefer-dist
#       - run: yarn upgrade node-sass@4.14.1
      - run: yarn install

      - run: yarn run ${{ matrix.script }}
